branches: {only: [master, test]}

sudo: false
language: python
cache: pip

matrix:
  include:
    - python: "3.6"
    - python: "3.5"
    - python: "3.4"
    - python: "2.7"
    - {env: TOXENV=style, python: "3.6"}
    - {env: TOXENV=requirements, python: "3.6"}
    - {env: TOXENV=packaging, python: "3.6"}

install:
  - pip install codecov tox-travis

script: tox

after_success:
  - codecov -e TRAVIS_PYTHON_VERSION
